export const PERMISSIONS = {
  USER_READ: 'USER_READ',
  USER_WRITE: 'USER_WRITE',

  BOOK_READ: 'BOOK_READ',
  BOOK_WRITE: 'BOOK_WRITE',

  INVENTORY_READ: 'INVENTORY_READ',
  INVENTORY_WRITE: 'INVENTORY_WRITE',

  BORROW_READ: 'BORROW_READ',
  BORROW_WRITE: 'BORROW_WRITE',

  RETURN_READ: 'RETURN_READ',
  RETURN_WRITE: 'RETURN_WRITE'
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];
